name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://fy2sysnotify:${GIT_TOKEN}@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository
          git clone https://github.com/fy2sysnotify/kubernetes-cicd-gitops.git gitops
          cd gitops

          
          
          # Update image in deployment.yaml
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|image: ghcr.io/fy2sysnotify/kubernetes-cicd-tutorial:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          else
            sed -i "s|image: ghcr.io/fy2sysnotify/kubernetes-cicd-tutorial:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          fi

          cat deployment.yaml
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          
          # Push changes
          git push https://fy2sysnotify:${GIT_TOKEN}@github.com/fy2sysnotify/kubernetes-cicd-gitops.git main
